name: Deploy to Firebase Functions on release (prod)
'on':
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Triggers when a tag like v1.0.0 is pushed
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - lszm_prod
          - lsze_prod
          - lszo_prod
          - lszt_prod
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Install Google Cloud SDK components
        run: |
          sudo apt-get install google-cloud-cli

      - name: Configure Google Cloud Project
        run: |
          gcloud config set project ${{ vars.FIREBASE_PROJECT }}

      - name: Delete old cardPaymentsStripe (Gen 1)
        run: |
          gcloud functions delete cardPaymentsStripe --region=us-central1 --quiet || true

      - name: Deploy Firebase Function (Go)
        run: |
          gcloud functions deploy cardPaymentsStripe \
            --gen2 \
            --entry-point=CardPaymentsStripe \
            --trigger-event-filters="type=google.firebase.database.ref.v1.created" \
            --trigger-event-filters="instance=${{ vars.FIREBASE_RTDB_NAME }}" \
            --trigger-event-filters-path-pattern="ref=card-payments/{pushId}" \
            --trigger-location=${{ vars.FUNCTION_REGION || 'europe-west1' }} \
            --region=${{ vars.FUNCTION_REGION || 'europe-west1' }} \
            --runtime=go122 \
            --set-env-vars=STRIPE_SECRET=${{ secrets.STRIPE_SECRET }},\
          RETURN_BASE_URL=${{ vars.RETURN_BASE_URL }},\
          TERMINAL_ID=${{ vars.TERMINAL_ID }},\
          FIREBASE_DATABASE_URL=${{ vars.FIREBASE_RTDB_URL }}

      - name: Delete old StripeWebhook (Gen 1)
        run: |
          gcloud functions delete StripeWebhook --region=us-central1 --quiet || true

      - name: Deploy Webhook Firebase Function (Go)
        run: |
          gcloud functions deploy StripeWebhook \
            --gen2 \
            --allow-unauthenticated \
            --trigger-http \
            --region=${{ vars.FUNCTION_REGION || 'europe-west1' }} \
            --runtime=go122 \
            --set-env-vars=WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }},\
          FIREBASE_DATABASE_URL=${{ vars.FIREBASE_RTDB_URL }}
